# Copyright © 2017 VMware, Inc. All Rights Reserved.
---

- include: install.yml
  when: vic_version != "remove"

- include: vic-create.yml

# doesn't work yet.
#- include: vic-delete.yml
#  when: vic_vch_delete

- include: uninstall.yml
  when: vic_version == "remove"
